lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = -16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 0;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 64;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 80;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 96;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 112;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 128;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 144;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 160;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 176;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 192;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 192;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 208;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 224;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 224;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 240;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 256;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 256;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 272;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 288;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 288;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 304;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 304;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 320;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 320;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 336;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 336;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 352;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 352;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 368;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 384;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 400;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 416;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 416;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 432;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 448;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 464;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 480;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 496;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 640;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 576;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384;
lastcreated.cell_y = 576;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 320;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128;
lastcreated.cell_y = 576;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 560;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 576;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 496;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 448;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 464;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 464;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 480;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 400;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 416;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 432;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 352;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 368;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 304;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 320;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 336;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 272;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 272;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 288;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 240;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 256;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 240;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 208;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 224;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 208;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 176;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 192;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 176;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 144;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 144;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 160;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 128;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 112;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = -32;
lastcreated.cell_y = 80;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 96;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 160;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 128;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 16;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 368;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 384;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512;
lastcreated.cell_y = 384;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 400;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 432;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 448;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512;
lastcreated.cell_y = 448;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 464;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 480;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 352;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384;
lastcreated.cell_y = 544;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 384;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 416;
lastcreated.cell_y = 496;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 496;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480;
lastcreated.cell_y = 464;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512;
lastcreated.cell_y = 480;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 448;
lastcreated.cell_y = 480;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 480;
lastcreated.cell_y = 496;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 496;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);

if (adjacent[0] != noone){
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_door;
lastcreated.entrance_id = 0;
entrance[0] = lastcreated;
ds_list_add(cell_list,lastcreated);
}else{
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 608;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 544;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 576;
lastcreated.cell_y = 64;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
}
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 512;
lastcreated.cell_y = 96;
lastcreated.cell_type = obj_empty_space;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
startlocation[0] = lastcreated;

if (adjacent[1] != noone){
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_door;
lastcreated.entrance_id = 1;
entrance[1] = lastcreated;
ds_list_add(cell_list,lastcreated);
}else{
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256;
lastcreated.cell_y = 32;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 288;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256;
lastcreated.cell_y = 64;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
}
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256;
lastcreated.cell_y = 128;
lastcreated.cell_type = obj_empty_space;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
startlocation[1] = lastcreated;

if (adjacent[2] != noone){
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 64;
lastcreated.cell_type = obj_door;
lastcreated.entrance_id = 2;
entrance[2] = lastcreated;
ds_list_add(cell_list,lastcreated);
}else{
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 48;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 64;
lastcreated.cell_y = 64;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 0;
lastcreated.cell_y = 64;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 32;
lastcreated.cell_y = 80;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
}
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 96;
lastcreated.cell_y = 112;
lastcreated.cell_type = obj_empty_space;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
startlocation[2] = lastcreated;

if (adjacent[3] != noone){
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_door;
lastcreated.entrance_id = 3;
entrance[3] = lastcreated;
ds_list_add(cell_list,lastcreated);
}else{
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = 496;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 256;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 192;
lastcreated.cell_y = 512;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = 528;
lastcreated.cell_type = obj_wall;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
}
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = 400;
lastcreated.cell_type = obj_empty_space;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
startlocation[3] = lastcreated;
lastcreated = instance_create(0,0,obj_abstract_cell);
lastcreated.cell_x = 224;
lastcreated.cell_y = 272;
lastcreated.cell_type = obj_empty_space;
lastcreated.chamber = id;
ds_list_add(cell_list,lastcreated);
startlocation_main = lastcreated;

